# Generated by Django 3.1.6 on 2021-02-11 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('opencpn_guid', models.CharField(blank=True, default='', max_length=150)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_from', models.CharField(blank=True, default='', max_length=100)),
                ('to', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('wind_force', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('wind_direction', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('becoming_wind_force', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('becoming_direction', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('plan_speed', models.DecimalField(decimal_places=1, default=5.5, max_digits=3)),
                ('distance', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('dtw', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('opencpn_extensions', models.JSONField(blank=True, null=True)),
                ('extensions', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TideRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TideStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WayPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, default='WPT', max_length=10)),
                ('symbol', models.CharField(blank=True, default='', max_length=80)),
                ('psym', models.CharField(blank=True, default='', max_length=80)),
                ('opencpn_guid', models.CharField(blank=True, default='', max_length=150)),
                ('raymarine_guid', models.CharField(blank=True, default='', max_length=150)),
                ('extensions', models.JSONField(blank=True, null=True)),
                ('opencpn_extensions', models.JSONField(blank=True, null=True)),
                ('links', models.JSONField(blank=True, null=True)),
                ('drift_factor', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('set_rotation', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tide_rates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.tiderate')),
                ('tide_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.tidestation')),
            ],
        ),
        migrations.CreateModel(
            name='TideRatePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrs', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('direction', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('spring', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('neap', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('tide_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.tiderate')),
            ],
        ),
        migrations.CreateModel(
            name='TideHeightPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrs', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('spring', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('neap', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tide_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.tidestation')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('number', models.IntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(blank=True, default='WPT', max_length=10)),
                ('symbol', models.CharField(blank=True, default='', max_length=80)),
                ('psym', models.CharField(blank=True, default='', max_length=80)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('extensions', models.JSONField(blank=True, null=True)),
                ('opencpn_extensions', models.JSONField(blank=True, null=True)),
                ('opencpn_guid', models.CharField(blank=True, default='', max_length=150)),
                ('arrival_radius', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('links', models.JSONField(blank=True, null=True)),
                ('drift_factor', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('set_rotation', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('set', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('drift', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('cts', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('smg', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.plan')),
                ('tide_rates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.tiderate')),
                ('tide_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.tidestation')),
                ('way_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.waypoint')),
            ],
        ),
    ]
