# Generated by Django 3.1.5 on 2021-02-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_from', models.CharField(max_length=200)),
                ('to', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('wind_force', models.DecimalField(decimal_places=0, max_digits=1)),
                ('wind_direction', models.DecimalField(decimal_places=0, max_digits=3)),
                ('becoming_wind_force', models.DecimalField(decimal_places=0, max_digits=1)),
                ('becoming_direction', models.DecimalField(decimal_places=0, max_digits=3)),
                ('plan_speed', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='PlanPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('eta', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('set', models.DecimalField(decimal_places=0, max_digits=3)),
                ('drift', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cts', models.DecimalField(decimal_places=0, max_digits=3)),
                ('smg', models.DecimalField(decimal_places=1, max_digits=3)),
                ('distance', models.DecimalField(decimal_places=1, max_digits=7)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.plan')),
            ],
        ),
    ]
