# Generated by Django 3.1.6 on 2021-02-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='guid',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='opencpn_guid',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='planner_guid',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='psym',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
