# Generated by Django 3.1.6 on 2021-02-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_auto_20210206_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waypoint',
            old_name='arrival_radius',
            new_name='extensions',
        ),
        migrations.RenameField(
            model_name='waypoint',
            old_name='range_rings',
            new_name='opencpn_extensions',
        ),
        migrations.RenameField(
            model_name='waypoint',
            old_name='guid',
            new_name='raymarine_guid',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='planner_guid',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='viz_name',
        ),
        migrations.AddField(
            model_name='waypoint',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='type',
            field=models.CharField(blank=True, default='WPT', max_length=10),
        ),
    ]
