# Generated by Django 3.1.6 on 2021-02-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_auto_20210213_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planpoint',
            name='merc_lat',
        ),
        migrations.RemoveField(
            model_name='planpoint',
            name='merc_long',
        ),
        migrations.RemoveField(
            model_name='planpoint',
            name='str_lat',
        ),
        migrations.RemoveField(
            model_name='planpoint',
            name='str_long',
        ),
        migrations.AlterField(
            model_name='planpoint',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='planpoint',
            name='long',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='long',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
