# Generated by Django 3.1.6 on 2021-02-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_auto_20210214_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='opencpn_guid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_from',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='to',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='planpoint',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='planpoint',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tiderate',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='tidestation',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddIndex(
            model_name='planpoint',
            index=models.Index(fields=['number', 'plan'], name='planning_pl_number_768207_idx'),
        ),
    ]
