# Generated by Django 3.1.6 on 2021-02-08 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_auto_20210206_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='opencpn_extensions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='opencpn_guid',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='planpoint',
            name='arrival_radius',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='planpoint',
            name='drift_factor',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='planpoint',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planpoint',
            name='links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planpoint',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planpoint',
            name='opencpn_extensions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planpoint',
            name='opencpn_guid',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='planpoint',
            name='psym',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='planpoint',
            name='set_rotation',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='planpoint',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='planpoint',
            name='tide_rates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.tiderate'),
        ),
        migrations.AddField(
            model_name='planpoint',
            name='tide_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.tidestation'),
        ),
    ]
