# Generated by Django 3.1.6 on 2021-02-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_auto_20210214_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpoint',
            name='fixed',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='planpoint',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
