# Generated by Django 3.1.6 on 2021-02-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_auto_20210208_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpoint',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
