# Generated by Django 3.1.6 on 2021-02-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_planpoint_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='dtw',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
    ]
