# Generated by Django 3.1.6 on 2021-02-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_planpoint_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tideratepoint',
            name='direction',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
    ]
