# Generated by Django 3.1.6 on 2021-02-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_auto_20210208_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='extensions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planpoint',
            name='extensions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
