# Generated by Django 3.1.6 on 2021-02-15 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_auto_20210215_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiderate',
            name='drift_factor',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='tiderate',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='tiderate',
            name='long',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='tiderate',
            name='set_rotation',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='tiderate',
            name='tide_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.tidestation'),
        ),
        migrations.CreateModel(
            name='TideTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('ht', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('high_water', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tide_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.tidestation')),
            ],
        ),
    ]
