# Generated by Django 3.1.6 on 2021-02-15 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_auto_20210215_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='view-plan',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('planning.plan',),
        ),
        migrations.RemoveField(
            model_name='planpoint',
            name='drift_factor',
        ),
        migrations.RemoveField(
            model_name='planpoint',
            name='set_rotation',
        ),
        migrations.RemoveField(
            model_name='planpoint',
            name='tide_station',
        ),
    ]
