# Generated by Django 3.1.6 on 2021-02-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_auto_20210215_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiderate',
            name='drift_factor',
        ),
        migrations.RemoveField(
            model_name='tiderate',
            name='set_rotation',
        ),
        migrations.AddField(
            model_name='planpoint',
            name='cog',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='tiderate',
            name='channel_flow',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
