# Generated by Django 3.1.6 on 2021-02-23 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_auto_20210217_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tidestation',
            name='hrs_difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='tidestation',
            name='tide_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.tidestation'),
        ),
    ]
