# Generated by Django 3.1.6 on 2021-02-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depthlog',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='depthlog',
            name='long',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='position',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='position',
            name='long',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='long',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
