# Generated by Django 3.1.6 on 2021-02-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passage',
            old_name='narrative',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='track',
            name='passage',
        ),
        migrations.AddField(
            model_name='passage',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='track',
            name='extensions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='opencpn_extensions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackpoint',
            name='extensions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackpoint',
            name='opencpn_extensions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
