# Generated by Django 3.1.5 on 2021-02-01 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('eng_log', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fuel_rate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('est_tank', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fuel_added', models.DecimalField(decimal_places=2, max_digits=6)),
                ('full_tank', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_from', models.CharField(max_length=200)),
                ('to', models.CharField(max_length=200)),
                ('towards', models.CharField(max_length=200)),
                ('narrative', models.TextField()),
                ('weather', models.TextField()),
                ('maintenance', models.TextField()),
                ('max_wind_force', models.DecimalField(decimal_places=0, max_digits=1)),
                ('max_wind_direction', models.DecimalField(decimal_places=0, max_digits=3)),
                ('min_wind_force', models.DecimalField(decimal_places=0, max_digits=1)),
                ('distance', models.DecimalField(decimal_places=1, max_digits=7)),
                ('fuel_used', models.DecimalField(decimal_places=1, max_digits=5)),
                ('day_hrs', models.DecimalField(decimal_places=1, max_digits=3)),
                ('night_hrs', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_from', models.CharField(max_length=200)),
                ('to', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('wind_force', models.DecimalField(decimal_places=0, max_digits=1)),
                ('wind_direction', models.DecimalField(decimal_places=0, max_digits=3)),
                ('becoming_wind_force', models.DecimalField(decimal_places=0, max_digits=1)),
                ('becoming_direction', models.DecimalField(decimal_places=0, max_digits=3)),
                ('plan_speed', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='SailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('wind_side', models.CharField(choices=[('p', 'port'), ('s', 'starboard'), ('a', 'stern/aft'), ('u', 'unknown')], default='u', max_length=1)),
                ('wind_force', models.DecimalField(decimal_places=0, max_digits=1)),
                ('wind_direction', models.DecimalField(decimal_places=0, max_digits=3)),
                ('sail_plan', models.CharField(choices=[('FS', 'Full Sail'), ('A1', 'All sails reef 1'), ('A2', 'All sails reef 1'), ('A3', 'All sails reef 3'), ('MF', 'Only Main Full'), ('M1', 'Only Main Reef 1'), ('M2', 'Only Main Reef 2'), ('M3', 'Only Main Reef 3'), ('GF', 'only Full Genoa'), ('G1', 'only Genoa reef 1'), ('G2', 'only Genoa reef 2'), ('G3', 'only Genoa reef 3'), ('NN', 'no sails')], default='NN', max_length=2)),
                ('spinnaker', models.BooleanField(default=False)),
                ('cruising_shoot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('wind_force', models.DecimalField(decimal_places=0, max_digits=1)),
                ('wind_direction', models.DecimalField(decimal_places=0, max_digits=3)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('humidity', models.DecimalField(decimal_places=0, max_digits=3)),
                ('pressure', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('log', models.DecimalField(decimal_places=3, max_digits=10)),
                ('eng_log', models.DecimalField(decimal_places=3, max_digits=10)),
                ('course', models.DecimalField(decimal_places=0, max_digits=3)),
                ('speed', models.DecimalField(decimal_places=0, max_digits=3)),
                ('sog', models.DecimalField(decimal_places=0, max_digits=3)),
                ('cog', models.DecimalField(decimal_places=0, max_digits=3)),
                ('depth', models.DecimalField(decimal_places=0, max_digits=3)),
                ('status', models.CharField(choices=[('MB', 'Moored/Berthed'), ('UW', 'under way'), ('ME', 'main engine'), ('UT', 'under tow'), ('TV', 'towing vessel'), ('AD', 'adrift'), ('AA', 'at anchor'), ('AG', 'aground'), ('HT', 'heaved too'), ('MS', 'Motor Sailing'), ('II', 'In Irons'), ('CH', 'Close Hauled'), ('CR', 'Close Reach'), ('BB', 'Beam Reach'), ('BR', 'Broad Reach'), ('RU', 'running under sail')], default='MB', max_length=2)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boat_log.passage')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('eta', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('set', models.DecimalField(decimal_places=0, max_digits=3)),
                ('drift', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cts', models.DecimalField(decimal_places=0, max_digits=3)),
                ('smg', models.DecimalField(decimal_places=1, max_digits=3)),
                ('distance', models.DecimalField(decimal_places=1, max_digits=7)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boat_log.plan')),
            ],
        ),
        migrations.AddField(
            model_name='passage',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boat_log.plan'),
        ),
    ]
