# Generated by Django 3.1.5 on 2021-02-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('eng_log', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fuel_rate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('est_tank', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fuel_added', models.DecimalField(decimal_places=2, max_digits=6)),
                ('full_tank', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('wind_force', models.DecimalField(decimal_places=0, max_digits=1)),
                ('wind_direction', models.DecimalField(decimal_places=0, max_digits=3)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('humidity', models.DecimalField(decimal_places=0, max_digits=3)),
                ('pressure', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
    ]
