# Generated by Django 3.1.6 on 2021-02-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxwritefile',
            name='extensions',
            field=models.CharField(choices=[('NO', 'Add No Extensions'), ('OP', 'OpenCPN'), ('RA', 'Raymarine')], default='AL', max_length=2, null=True),
        ),
    ]
